<a href="https://colab.research.google.com/github/huberth117/hello-world/blob/master/Clase_02_Numpy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [ ]:
import numpy as np
l = [1,2,3]
m = [4,5,6]
a=np.array(l)
b=np.array(m)
print(a)
print(m)


[1 2 3]
[4, 5, 6]


TypeError: ignored

Podemos concatenar más de dos arreglos al tiempo:

`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [ ]:
# dimensiones mixtas
a = np.array([[1,2], [3,4]])
b=np.arange(5, 11).reshape(2,3)
print(a)
print(b)

#np.vstack([a, b])


[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


In [ ]:
#No se puede hacer si presentan dimensionalidad diferente


Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [ ]:
#dimensiones mixtas


In [ ]:
#arreglos unidimensionales


<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos.




In [ ]:
a = np.arange(8)

print(f"a: {a}")
print()
print(f"a[3]: {a[3]}")
print()
print(f"a[2:6]: {a[2:6]}")

a: [0 1 2 3 4 5 6 7]

a[3]: 3

a[2:6]: [2 3 4 5]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [ ]:
# definiendo una lista de listas de forma (3,3)
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [ ]:
l_arr = np.array(L)
l_arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
for fila in L:
  print(fila[:2])

[1, 2]
[4, 5]
[7, 8]


El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$).

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [ ]:
l_arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [ ]:
#creamos un arreglo de dimensiones 4x4
a= np.arange(16).reshape(4,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#seleccionar la primer fila (equivalente a a[0,:])
a[0,:]


array([0, 1, 2, 3])

In [ ]:
# seleccionar la primera columna
a[:,0]

array([ 0,  4,  8, 12])

In [ ]:
#segmentar las filas pares y las columnas impares.
a[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a[::1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#segmentar la matriz interna de 2x2.
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2: : -1, :3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
a=np.array([1, 2, 3, 2, 4,6,1,2,12,0,-12,6]).reshape(4,3)
print(a)
np.mean(a,axis=1)

[[  1   2   3]
 [  2   4   6]
 [  1   2  12]
 [  0 -12   6]]


array([ 2.,  4.,  5., -2.])

<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [ ]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar.

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [ ]:
# numero de elementos menores a 6
x[x < 5]

array([0, 1, 2, 3, 4])

5

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [ ]:
# numero de elementos menores a 6 por columna
np.sum(x < 5)

5

In [ ]:
# numero de elementos menores a 6 por fila
np.sum(x < 5, axis =1)

array([3, 2, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [ ]:
# verdadero si ambos verdaderos
np.sum((x >1) & (x < 5))

3

In [ ]:
# verdadero en caso en que alguno de los dos sea verdadero
np.sum((x <1) | (x > 5))

4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos.

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [ ]:
x[x < 5]

array([0, 1, 2, 3, 4])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, muestre:

* Un arreglo con los primeros números pares hasta `n`.
* Un arreglo con los primeros números múltiplos de tres hasta `n`.

In [ ]:
def f():
  a=np.arange(9)
  print(a[(a % 2)==0])
  print(a[np.mod(a,3)==0] )
f()

[0 2 4 6 8]
[0 3 6]


**Ejercicio 3:** Escribir un programa que lea `n` números enteros, calcule y muestre la suma de los pares y el producto de los impares.

In [ ]:
#arg vbles y entrada de usr

<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [ ]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#extraer indices 0,4 y 6
print(a[0], a[4], a[6])
#mejor
indices= [0, 4, 6]
a[indices]

0 4 6


array([0, 4, 6])

Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [ ]:
# creamos arreglo de indices con forma (2,2)
indi = np.array([[3, 7],[4, 9]])
indi
a[indi]

array([[13, 17],
       [14, 19]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo: